// <auto-generated />
using System;
using Ada.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ada.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240320150153_AddCoursesToDatabase")]
    partial class AddCoursesToDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ada.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Azure"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "AWS"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Sitefinity"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Generative AI"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Terraform"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Databricks"
                        });
                });

            modelBuilder.Entity("Ada.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Online")
                        .HasColumnType("bit");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<double?>("Price4")
                        .HasColumnType("float");

                    b.Property<double?>("PricePrivate")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A 3 day Training Class on ASP.NET 8 Development using the latest version of Visual Studio",
                            Instructor = "Lino Tadros",
                            Online = true,
                            Price = 2250.0,
                            Price4 = 1999.0,
                            PricePrivate = 15000.0,
                            Title = "ASP.NET Core 8 for Developers"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A 3 day Training Class of Microsoft Fabric for Data Analytics",
                            Instructor = "Lino Tadros",
                            Online = true,
                            Price = 3000.0,
                            Price4 = 2600.0,
                            PricePrivate = 25000.0,
                            Title = "Mastering Microsoft Fabric"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A 2 day Training Class for Sitefinity development using MVC in ASP.NET",
                            Instructor = "Lino Tadros",
                            Online = true,
                            Price = 1599.0,
                            Price4 = 1299.0,
                            PricePrivate = 12000.0,
                            Title = "Mastering Sitefinity Development"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
